name: cognitive_services
version: 0.0.2
description: >
  An unofficial Microsoft Azure Cognitive Services wrapper for all Dart platforms (Web, VM, Flutter)
author: Michael John Peña <mjtpena@outlook.com>
homepage: https://github.com/mjtpena/cognitive-dart
environment:
  sdk: ">=1.0.0 <3.0.0"
dependencies:
  convert: ">=1.0.0 <3.0.0"
dev_dependencies:
  test: any
